//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 11:24:15 AM GMT+01:00 
//


package allapis.springbootsoap.com;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the allapis.springbootsoap.com package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: allapis.springbootsoap.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddStudentResponse }
     * 
     */
    public AddStudentResponse createAddStudentResponse() {
        return new AddStudentResponse();
    }

    /**
     * Create an instance of {@link AddAdminResponse }
     * 
     */
    public AddAdminResponse createAddAdminResponse() {
        return new AddAdminResponse();
    }

    /**
     * Create an instance of {@link TeacherInfo }
     * 
     */
    public TeacherInfo createTeacherInfo() {
        return new TeacherInfo();
    }

    /**
     * Create an instance of {@link GetAdminByIdRequest }
     * 
     */
    public GetAdminByIdRequest createGetAdminByIdRequest() {
        return new GetAdminByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteAdminRequest }
     * 
     */
    public DeleteAdminRequest createDeleteAdminRequest() {
        return new DeleteAdminRequest();
    }

    /**
     * Create an instance of {@link AdminInfo }
     * 
     */
    public AdminInfo createAdminInfo() {
        return new AdminInfo();
    }

    /**
     * Create an instance of {@link UpdateAdminResponse }
     * 
     */
    public UpdateAdminResponse createUpdateAdminResponse() {
        return new UpdateAdminResponse();
    }

    /**
     * Create an instance of {@link DeleteAdminResponse }
     * 
     */
    public DeleteAdminResponse createDeleteAdminResponse() {
        return new DeleteAdminResponse();
    }

    /**
     * Create an instance of {@link ServiceStatusStudent }
     * 
     */
    public ServiceStatusStudent createServiceStatusStudent() {
        return new ServiceStatusStudent();
    }

    /**
     * Create an instance of {@link GetStudentResponse }
     * 
     */
    public GetStudentResponse createGetStudentResponse() {
        return new GetStudentResponse();
    }

    /**
     * Create an instance of {@link GetTeacherResponse }
     * 
     */
    public GetTeacherResponse createGetTeacherResponse() {
        return new GetTeacherResponse();
    }

    /**
     * Create an instance of {@link UpdateTeacherResponse }
     * 
     */
    public UpdateTeacherResponse createUpdateTeacherResponse() {
        return new UpdateTeacherResponse();
    }

    /**
     * Create an instance of {@link StudentInfo }
     * 
     */
    public StudentInfo createStudentInfo() {
        return new StudentInfo();
    }

    /**
     * Create an instance of {@link DeleteTeacherResponse }
     * 
     */
    public DeleteTeacherResponse createDeleteTeacherResponse() {
        return new DeleteTeacherResponse();
    }

    /**
     * Create an instance of {@link UpdateTeacherRequest }
     * 
     */
    public UpdateTeacherRequest createUpdateTeacherRequest() {
        return new UpdateTeacherRequest();
    }

    /**
     * Create an instance of {@link AddTeacherResponse }
     * 
     */
    public AddTeacherResponse createAddTeacherResponse() {
        return new AddTeacherResponse();
    }

    /**
     * Create an instance of {@link AddStudentRequest }
     * 
     */
    public AddStudentRequest createAddStudentRequest() {
        return new AddStudentRequest();
    }

    /**
     * Create an instance of {@link GetAdminResponse }
     * 
     */
    public GetAdminResponse createGetAdminResponse() {
        return new GetAdminResponse();
    }

    /**
     * Create an instance of {@link ServiceStatusTeacher }
     * 
     */
    public ServiceStatusTeacher createServiceStatusTeacher() {
        return new ServiceStatusTeacher();
    }

    /**
     * Create an instance of {@link DeleteStudentRequest }
     * 
     */
    public DeleteStudentRequest createDeleteStudentRequest() {
        return new DeleteStudentRequest();
    }

    /**
     * Create an instance of {@link UpdateStudentRequest }
     * 
     */
    public UpdateStudentRequest createUpdateStudentRequest() {
        return new UpdateStudentRequest();
    }

    /**
     * Create an instance of {@link DeleteStudentResponse }
     * 
     */
    public DeleteStudentResponse createDeleteStudentResponse() {
        return new DeleteStudentResponse();
    }

    /**
     * Create an instance of {@link GetTeacherByIdRequest }
     * 
     */
    public GetTeacherByIdRequest createGetTeacherByIdRequest() {
        return new GetTeacherByIdRequest();
    }

    /**
     * Create an instance of {@link AddAdminRequest }
     * 
     */
    public AddAdminRequest createAddAdminRequest() {
        return new AddAdminRequest();
    }

    /**
     * Create an instance of {@link DeleteTeacherRequest }
     * 
     */
    public DeleteTeacherRequest createDeleteTeacherRequest() {
        return new DeleteTeacherRequest();
    }

    /**
     * Create an instance of {@link ServiceStatusAdmin }
     * 
     */
    public ServiceStatusAdmin createServiceStatusAdmin() {
        return new ServiceStatusAdmin();
    }

    /**
     * Create an instance of {@link AddTeacherRequest }
     * 
     */
    public AddTeacherRequest createAddTeacherRequest() {
        return new AddTeacherRequest();
    }

    /**
     * Create an instance of {@link UpdateAdminRequest }
     * 
     */
    public UpdateAdminRequest createUpdateAdminRequest() {
        return new UpdateAdminRequest();
    }

    /**
     * Create an instance of {@link GetStudentByIdRequest }
     * 
     */
    public GetStudentByIdRequest createGetStudentByIdRequest() {
        return new GetStudentByIdRequest();
    }

    /**
     * Create an instance of {@link UpdateStudentResponse }
     * 
     */
    public UpdateStudentResponse createUpdateStudentResponse() {
        return new UpdateStudentResponse();
    }

}
